### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by yangchangqu** [Saber2pr/ts-compiler#1]
安装最新版本依赖，导入函数并调用：
`import {runCode} from '@saber2pr/ts-compiler';
runCode(codeStr.value);`
然后就报错了！！！
![Uploading QQ截图20231208164001.png…]()

**Comment by yangchangqu** [comment]
作者，你好！有空可以帮忙看看是我哪里没弄好？我只是想在页面上手写一段ts代码，然后动态编译并执行。是否就是使用`runCode`这个函数？

**Comment by yangchangqu** [comment]
ReferenceError: process is not defined
    at node_modules/graceful-fs/polyfills.js (polyfills.js:3:15)
    at __require2 (chunk-W7S2ME4R.js?v=09e0c1ed:18:50)
    at node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:2:17)
    at __require2 (chunk-W7S2ME4R.js?v=09e0c1ed:18:50)
    at node_modules/@saber2pr/ts-compiler/lib/compiler/read-exports.js (read-exports.js:7:39)
    at __require2 (chunk-W7S2ME4R.js?v=09e0c1ed:18:50)
    at node_modules/@saber2pr/ts-compiler/lib/compiler/index.js (index.js:18:14)
    at __require2 (chunk-W7S2ME4R.js?v=09e0c1ed:18:50)
    at node_modules/@saber2pr/ts-compiler/lib/index.js (index.js:30:14)
    at __require2 (chunk-W7S2ME4R.js?v=09e0c1ed:18:50)

**Comment by Saber2pr** [comment]
process是nodejs的全局变量，你是在web浏览器端使用了吗

**Comment by Saber2pr** [comment]
<img width="524" alt="image" src="https://github.com/Saber2pr/ts-compiler/assets/40260564/51bbeafc-e888-4751-ada8-5081d0a5d949">

**Comment by yangchangqu** [comment]
对的，我在浏览器端使用了。

**Comment by yangchangqu** [comment]
您有什么方案可以在浏览器上编译运行吗？
这个链接上有个截图看起来是可以做到：https://www.zhihu.com/question/294177134
好像那个在线编辑器是同一个作者，也是你-。-!

**Comment by Saber2pr** [comment]
那个是monaco的功能，typescript有个lib是可以在浏览器端运行的。可以参考一下这个 https://github.com/Saber2pr/editor

https://github.com/Saber2pr/editor/blob/9a233e115383a74505f9dbdb12f3207974cab553/src/core/typescript.ts#L15-L21
